version: '3'
services:
  dockerapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis:7.4.2
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
