version: 2
jobs:
  working_directory: /dockerapp
  docker:
    - image: docker:27.5.1-cli
    - steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Install dependencies
        command: |
          apk add --no-cache py-pip=25.0
          pip install docker-compose==1.29.2
      - run:
        name: Run tests
        command: |
          docker-compose up -d
          docker-compose run dockerapp python tests.py
